classDiagram

    class TipoUsuario{
        - STRING TipoUs
    }

    class Usuario{
        - STRING Email
        - STRING Contraseña

        + cambiarContrasena()
        + crearTarea()
        + crearEvento()
        + agregarDonacion()
        + agregarOperacion()
        + agregarInventario() 
	+ registrarse()  
    }

    class Org{
        - STRING Nombre
        - STRING LinkForm
        - STRING Logo
        - STRING SitioWeb

        + subirLogo()
    }

    class Candidato{
        - STRING Nombre
        - STRING Apellido
        - DATE FechaNacimiento
        - DATE DiasDisp
        - TIME HorasDisp
        - STRING Descripcion

	+ enviarFormulario()
        + generarEtiquetas()
    }

    class CandidatoxUsuario{
    }

    class Etiqueta{
        - STRING Nombre
    }

    class EtiquetaxCandidato{
    }

    class TipoEtiqueta{
        - STRING TipoEt
    }

    class Persona{
        - STRING Nombre
        - STRING Apellido
        - STRING Telefono
        - DATE FechaNacimiento
    }

    class PersonaxEtiqueta{
    }

    class Evento{
        - STRING Nombre
        - STRING Descripcion
        - DATE FechaEvento
        - TIME HoraEvento

	+ listarEventos()
	+ editarEvento()
	+ crearEvento()
    }

    class Reporte{
        - STRING Reporte

	+ generarReporte()
    }

    class Tarea{
        - STRING Nombre
        - STRING Descripcion
        - DATE FechaTarea
        - TIME HoraTarea
        - STRING PublicoDirigido
   
	+ listarTareas()
	+ editarTarea()
	+ crearTarea()
	+ dirigirTarea()
    }

    class CategoriaProducto{
        - STRING Nombre
    }

    class Producto{
        - STRING Nombre
    }

    class EstadoProducto{
        - STRING EstadoProd
    }

    class Sede{
        - STRING Nombre
    }

    class Inventario{
        - INT Cantidad
	
	+ listarInventariosPorSede()
	+ cambiarCantidad()
    }

    class ProductoxInventario{
    }

    class Donacion{
        - STRING Descripcion
        - INT Monto

	+ listarDonaciones()
	+ agregarDonacion()
	+ editarDonacion()
    }

    class TipoOperacion{
        - STRING TipoOp
    }

    class Operacion{
        - STRING Descripcion
        - STRING Factura
    
	+ listarOperaciones()
	+ agregarOperacion()
	+ editarOperacion()
    }

    class ProductoxOperacion{
    }

    class Video{
        - STRING Titulo
        - STRING Descripcion
        - STRING LinkVideo

	+ subirVideo()
	+ listarVideos()
	+ editarDescripcionTitulo()
    }
