classDiagram

Org --> Usuario : tiene
Org ..> Donacion : guarda
Org ..> Operacion : realiza
Org ..> Tarea : crea
Org ..> Sede : tiene
Org o-- Candidato : tiene
Org ..> Video : sube
TipoUsuario ..> Usuario : tiene
Usuario --> Persona : tiene
Sede o-- Inventario : tiene
Inventario --> ProductoxInventario : tiene
Producto --> ProductoxInventario : tiene
Producto --> Categoria : tiene
Producto --> EstadoProducto : tiene
Producto --> ProductoXOperacion : tiene
DonacionXProducto --> Producto : tiene
DonacionXProducto --> Donacion : tiene
TareaxPersona --> Persona : tiene
Persona --> PersonaxEvento : tiene
Etiqueta --> EtiquetaXCandidato : tiene
Etiqueta --> TipoEtiqueta : tiene
Etiqueta --> PersonaXEtiqueta : tiene
Operacion --> TipoOperacion : tiene
ProductoXOperacion --> Operacion : tiene
Evento --* Reporte : genera
PersonaxEvento --> Evento : tiene
Evento --* Invitado : tiene
Tarea --> TareaxPersona : tiene
Candidato --> EtiquetaxCandidato
EtiquetaxCandidato --> Etiqueta
PersonaxEtiqueta --> Etiqueta
Persona --> PersonaxEtiqueta


    class TipoUsuario {
        - STRING tipousuario
        - INT nivelPermiso
    }

    class Usuario {
        - STRING correo
        - STRING contrasena

        + cambiarContrasena()
        + crearTarea()
        + crearEvento()
        + agregarDonacion()
        + agregarOperacion()
        + agregarInventario() 
	    + registrarse()  
    }

    class Org {
        - STRING nombre
        - STRING descripcion
        - STRING direccion
        - STRING telefono
        - STRING logo
        - STRING correo
        - STRING web

        + subirLogo()
    }

    class Candidato {
        - STRING nombre
        - STRING apellido
        - STRING correo
        - STRING telefono
        - TIME disponibilidad
        - DATE fechaNacimiento

        + enviarFormulario()
        + generarEtiquetas()
    }

    class Sede {
        - STRING nombre
        - STRING direccion
    }

    class Inventario{

        + listarInventariosPorSede()
        + cambiarCantidad()
    }

        class Producto {
        - STRING nombre
        - STRING descripcion
    }

    class Categoria {
        - STRING nombre
    }

    class EstadoProducto {
        - STRING descripcion
    }

    class Donacion {
        - DATE fecha
        - STRING descripcion

        + listarDonaciones()
        + agregarDonacion()
        + editarDonacion()
    }

    class DonacionXProducto{
        - STRING nombre
    }


    class Operacion {
        - DATE fecha
        - STRING descripcion
        - STRING Factura

        + listarOperaciones()
        + agregarOperacion()
        + editarOperacion()
    }

    class TipoOperacion {
        - STRING descripcion
    }

    class ProductoXOperacion{
        - STRING nombre
    }

    class Video {
        - STRING titulo
        - STRING url
        - STRING descripcion

        + subirVideo()
        + listarVideos()
        + editarDescripcionTitulo()
    }

    class Evento {
        - STRING titulo
        - STRING descripcion
        - DATE fecha
        - TIME hora

        + listarEventos()
        + editarEvento()
        + crearEvento()
    }

    class Reporte {
        - STRING Reporte

	    + generarReporte()
    }


    class Tarea {
        - STRING Nombre
        - STRING Descripcion
        - DATE FechaTarea
        - TIME HoraTarea
        - STRING PublicoDirigido

        + listarTareas()
        + editarTarea()
        + crearTarea()
        + dirigirTarea()
    }

    class Persona {
        - STRING nombre
        - STRING apellido
        - STRING telefono
        - STRING contrasena
    }

    class Etiqueta {
        - STRING nombre
    }

    class TipoEtiqueta {
        - STRING Nombre
    }

    class Invitado {
        - STRING nombre
        - STRING apellido
        - STRING telefono
    }

    class TareaxPersona{
        - STRING nombre
    }

    class PersonaxEvento{
        - STRING nombre
    }
    
    class PersonaXEtiqueta{
        - STRING nombre
    }

    class EtiquetaXCandidato{
        - STRING nombre
    }
