erDiagram

ONG ||--|| Usuario : tiene
ONG ||--|{ Donaciones : tiene
ONG ||--|{ Operacion : tiene
ONG ||--|{ Tarea : tiene
ONG ||--|{ Sede : tiene
ONG ||--|{ Candidato : tiene
ONG ||--|{ Video : tiene
Usuario }|--|| TipoUsuario : tiene
Usuario ||--|| Persona : tiene
Sede ||--|| Inventario : tiene
Inventario ||--|{ ProductoxInventario : tiene
Producto ||--|{ ProductoxInventario : tiene
Producto }|--|| Categoria : tiene
Producto }|--|| EstadoProducto : tiene
ProductoXOperacion }|--|| Producto : tiene
DonacionXProducto }|--|| Producto : tiene
DonacionXProducto }|--|| Donaciones : tiene
TareaxPersona }|--|| Persona : tiene
Persona ||--|{ PersonaxEvento : tiene
Persona ||--|{ PersonaXEtiqueta : tiene
Etiqueta ||--|{ EtiquetaXCandidato : tiene
Etiqueta }|--|| TipoEtiqueta : tiene
Etiqueta ||--|{ PersonaXEtiqueta : tiene
Operacion }|--|| TipoOperacion : tiene
Operacion ||--|{ ProductoXOperacion : tiene
Evento ||--|| Reporte : tiene
PersonaxEvento }|--|| Evento : tiene
Evento ||--|{ Invitado : tiene
Tarea ||--|{ TareaxPersona : tiene
EtiquetaXCandidato }|--|| Candidato : tiene

    TipoUsuario {
        int idTipoUsuario PK
        varchar descripcion
        int nivelPermiso
    }

    Inventario{
        int idInventario PK
        int idSede FK
    }

    Sede{
        int idSede PK
        varchar nombre
        varchar direccion
    }

    Producto{
        int idProducto PK
        varchar nombre
        varchar descripcion
        int idCategoria FK
        int idEstadoProducto FK
    }

    Categoria{
        int idCategoria PK
        varchar nombre
    }

    ProductoxInventario{
        int idProductoXInventario PK
        int idProducto FK
        int idInventario FK
    }

    EstadoProducto{
        int idEstadoProducto PK
        varchar descripcion
    }
   
    Donaciones{
        int idDonacion PK
        int idProducto FK
        int idUsuario FK
        date fecha
        varchar descripcion
    }

    DonacionXProducto{
        int idDonacionXProducto PK
        int idDonacion FK
        int idProducto FK
    }

    Operacion{
        int idOperacion PK
        int idTipoOperacion FK
        int idUsuario FK
        date fecha
        varchar descripcion
    }

    TipoOperacion{
        int idTipoOperacion PK
        varchar descripcion
    }

    ProductoXOperacion{
        int idProductoXOperacion PK
        int idProducto FK
        int idOperacion FK
    }

    Video{
        int idVideo PK
        varchar titulo
        varchar url
        varchar descripcion
        int idUsuario FK
    }
    %%Tare y Evento tiene los mismo atributos, podemos crear una sola entidad con un atributo tipo
    Tarea{
        int idTarea PK
        varchar titulo
        varchar descripcion
        date fecha
        time hora
        int idUsuario FK
    }

    Evento{
        int idEvento PK
        varchar titulo
        varchar descripcion
        date fecha
        time hora
        int idUsuario FK
    }

    Reporte{
        int idReporte PK
        varchar titulo
        varchar descripcion
        int idEvento FK
        int idUsuario FK
    }

    Usuario{
        int idUsuario PK
        varchar nombre
        varchar apellido
        varchar correo
        varchar contrasena
        int idTipoUsuario FK
    }

    Persona{
        int idPersona PK
        varchar nombre
        varchar apellido
        varchar telefono
        varchar contrasena
        int Usuario FK
        int idCategoriaUsuario FK
    }

    Etiqueta{
        int idEtiqueta PK
        varchar nombre
    }

    TipoEtiqueta{
        int idTipoEtiqueta PK
        varchar descripcion
    }

    PersonaXEtiqueta{
        int idPersonaXEtiqueta PK
        int idPersona FK
        int idEtiqueta FK
    }

    Candidato{
        int idCandidato PK
        varchar nombre
        varchar apellido
        varchar correo
        varchar telefono
        time disponibilidad
        date fechaNacimiento
    }

    EtiquetaXCandidato{
        int idEtiquetaXCandidato PK
        int idEtiqueta FK
        int idCandidato FK
    }

    ONG{
        int idONG PK
        varchar nombre
        varchar descripcion
        varchar direccion
        varchar telefono
        varchar logo
        varchar correo
        varchar web
        int idUsuario FK
    }

    Invitado{
        int idInvitado PK
        varchar nombre
        varchar apellido
        varchar telefono
        int idEvento FK
    }

    TareaxPersona{
        int idTareaxPersona PK
        int idTarea FK
        int idPersona FK
    }

    PersonaxEvento{
        int idPersonaxEvento PK
        int idEvento FK
        int idPersona FK
    }



