# Generated by Django 4.2.13 on 2024-07-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTagDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tag')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
    ]
