# Generated by Django 4.2.13 on 2024-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
