# Generated by Django 4.2.13 on 2024-07-01 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
