# Generated by Django 4.2.13 on 2024-07-04 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='request_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
