# Generated by Django 4.2.13 on 2024-05-20 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.usertype'),
        ),
    ]
